### PR TITLE
Create Simple Benchmarking Tool

### PR DESCRIPTION
**Pull request by lussierc**
This pull request will contain the code for a simple benchmarking tool that times a function running multiple rounds of a doubling experiment. A simple results table will be produced containing the results of the doubling experiment.

This will help users get a general idea of how long Speed-Surprises functions take to run and get a sense of its worst-case time complexity. This would be useful for members of the TaDa! team for confirming that things are functioning correctly as mentioned in Issue #13.

**Sample Run:**
Run Command:
```
python3 benchmark.py -m speedsurprises.lists.sets -f is_subset -t list,list
```
Ouput:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for is_subset ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 1.811981201171875e-05  |         0          |
|   2   |  200  | 5.221366882324219e-05  | 2.8815789473684212 |
|   3   |  400  |  6.4849853515625e-05   | 1.2420091324200913 |
|   4   |  800  | 0.00010704994201660156 | 1.650735294117647  |
|   5   |  1600 | 0.00019097328186035156 | 1.7839643652561248 |
|   6   |  3200 | 0.0003540515899658203  | 1.853932584269663  |
|   7   |  6400 | 0.0006701946258544922  | 1.892929292929293  |
|   8   | 12800 |  0.001341104507446289  | 2.001067235859125  |
|   9   | 25600 |  0.002708911895751953  | 2.019911111111111  |
|   10  | 51200 |  0.004143953323364258  | 1.5297482837528604 |
+-------+-------+------------------------+--------------------+
```

This pull request is currently a work in progress, I will attempt to provide updates regarding my progress in this pull request.

### CODE REVIEW

**Comment by lussierc** [comment]
I have a simple version of the Speed-Surprises benchmarking tool working.

Here is a benchmark done with the compute_factorial function using the command:
```
python3 benchmark.py -m speedsurprises.numbers.factorial -f compute_factorial -t int
```

Tool in action:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for compute_factorial ...
+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 2.5033950805664062e-05 |         0          |
|   2   |  200  | 4.696846008300781e-05  | 1.8761904761904762 |
|   3   |  400  | 0.00015878677368164062 | 3.3807106598984773 |
|   4   |  800  | 0.0003268718719482422  | 2.0585585585585586 |
|   5   |  1600 | 0.0010790824890136719  | 3.301239970824216  |
|   6   |  3200 | 0.0034818649291992188  | 3.2266902342023864 |
|   7   |  6400 |  0.010634899139404297  | 3.0543686661188714 |
|   8   | 12800 |  0.03879809379577637   | 3.6481863426444874 |
|   9   | 25600 |   0.1527390480041504   | 3.9367668114864407 |
|   10  | 51200 |   0.6683988571166992   | 4.376083692092521  |
+-------+-------+------------------------+--------------------+
```

**Comment by huangs1** [comment]
Here are the results tables for all the functions we have (the ones we created and the ones that were originally there) However there are some that either can't be run (the ones in `squareroot.py`) or takes too long to run (Recursive Fibonacci):

InsertionSort:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for insertion_sort ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 9.560585021972656e-05  |         0          |
|   2   |  200  | 0.00015354156494140625 | 1.6059850374064837 |
|   3   |  400  | 0.0002613067626953125  | 1.7018633540372672 |
|   4   |  800  | 0.00048661231994628906 | 1.8622262773722629 |
|   5   |  1600 | 0.0009701251983642578  | 1.9936305732484076 |
|   6   |  3200 |  0.00185394287109375   | 1.9110346522487098 |
|   7   |  6400 |  0.003368854522705078  | 1.8171296296296295 |
|   8   | 12800 | 0.0019335746765136719  | 0.5739561217268223 |
|   9   | 25600 | 0.0058248043060302734  | 3.0124537607891493 |
|   10  | 51200 |  0.007012605667114258  | 1.2039212475952683 |
+-------+-------+------------------------+--------------------+
```

Bubble Sort:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for bubble_sort ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+-----------------------+--------------------+
| Round |  Size |        Runtime        |      Average       |
+-------+-------+-----------------------+--------------------+
|   1   |  100  |  0.001383066177368164 |         0          |
|   2   |  200  |  0.005312919616699219 | 3.841406654025168  |
|   3   |  400  | 0.0069963932037353516 | 1.3168641177526477 |
|   4   |  800  |  0.023162364959716797 | 3.3106150962685295 |
|   5   |  1600 |  0.09518885612487793  | 4.109634585692229  |
|   6   |  3200 |  0.38617634773254395  | 4.056949137259519  |
|   7   |  6400 |   1.5558345317840576  | 4.028818804981784  |
|   8   | 12800 |   6.174164533615112   |  3.96839407243087  |
|   9   | 25600 |   24.59201669692993   | 3.9830517251426003 |
|   10  | 51200 |   102.63350796699524  | 4.173448206051682  |
+-------+-------+-----------------------+--------------------+

```

Merge Sort:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for merge_sort ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+-----------------------+--------------------+
| Round |  Size |        Runtime        |      Average       |
+-------+-------+-----------------------+--------------------+
|   1   |  100  | 0.0008928775787353516 |         0          |
|   2   |  200  | 0.0018782615661621094 | 2.1036048064085446 |
|   3   |  400  |  0.003729581832885742 | 1.9856562579334855 |
|   4   |  800  |  0.003119230270385742 | 0.8363485264974749 |
|   5   |  1600 |  0.007261037826538086 | 2.3278300084078576 |
|   6   |  3200 |  0.01166391372680664  | 1.606370054178296  |
|   7   |  6400 |  0.022913455963134766 | 1.9644740607497648 |
|   8   | 12800 |  0.049353599548339844 | 2.1539133873015213 |
|   9   | 25600 |  0.10434675216674805  | 2.114268323317424  |
|   10  | 51200 |  0.21540045738220215  | 2.0642756282245203 |
+-------+-------+-----------------------+--------------------+

```

Reverse:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for reverse ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 0.0001404285430908203  |         0          |
|   2   |  200  | 0.00023126602172851562 | 1.6468590831918506 |
|   3   |  400  | 0.0004966259002685547  | 2.147422680412371  |
|   4   |  800  | 0.0011298656463623047  | 2.2750840134421506 |
|   5   |  1600 |  0.003643035888671875  | 3.2243089259337414 |
|   6   |  3200 |  0.004084348678588867  | 1.1211387434554974 |
|   7   |  6400 | 0.0069544315338134766  | 1.7027027027027026 |
|   8   | 12800 |  0.031311988830566406  | 4.502451232472831  |
|   9   | 25600 |   0.1186668872833252   | 3.7898227393171506 |
|   10  | 51200 |   0.5631868839263916   | 4.745948063689789  |
+-------+-------+------------------------+--------------------+
```

Bcopies_Oft:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for bcopies_oft ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 5.817413330078125e-05  |         0          |
|   2   |  200  | 7.796287536621094e-05  | 1.3401639344262295 |
|   3   |  400  | 0.00014925003051757812 | 1.9143730886850152 |
|   4   |  800  | 0.00028824806213378906 | 1.9313099041533546 |
|   5   |  1600 | 0.0005805492401123047  | 2.0140612076095947 |
|   6   |  3200 | 0.0011670589447021484  | 2.0102669404517455 |
|   7   |  6400 | 0.0019903182983398438  | 1.7054136874361594 |
|   8   | 12800 |  0.001310586929321289  | 0.6584810733109727 |
|   9   | 25600 |  0.002589702606201172  | 1.9759869019465164 |
|   10  | 51200 |  0.005806446075439453  | 2.2421285214509297 |
+-------+-------+------------------------+--------------------+
```
Is_Subset:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for is_subset ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 2.1457672119140625e-05 |         0          |
|   2   |  200  | 3.266334533691406e-05  | 1.5222222222222221 |
|   3   |  400  |  6.29425048828125e-05  | 1.927007299270073  |
|   4   |  800  | 0.0001246929168701172  | 1.981060606060606  |
|   5   |  1600 | 0.0002608299255371094  | 2.0917782026768643 |
|   6   |  3200 |  0.000492095947265625  | 1.886654478976234  |
|   7   |  6400 | 0.0009844303131103516  | 2.000484496124031  |
|   8   | 12800 | 0.0023186206817626953  | 2.355291838217486  |
|   9   | 25600 |  0.004888296127319336  | 2.1082776349614396 |
|   10  | 51200 |  0.005183696746826172  | 1.0604301809491294 |
+-------+-------+------------------------+--------------------+
```
Iterative Factorial:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for compute_iterative_factorial ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 9.489059448242188e-05  |         0          |
|   2   |  200  | 0.00016617774963378906 | 1.7512562814070352 |
|   3   |  400  | 0.0003161430358886719  | 1.9024390243902438 |
|   4   |  800  | 0.0008654594421386719  | 2.737556561085973  |
|   5   |  1600 | 0.0028791427612304688  | 3.3267217630853994 |
|   6   |  3200 |  0.008801698684692383  | 3.057055316329911  |
|   7   |  6400 |  0.01108860969543457   | 1.2598260963783623 |
|   8   | 12800 |  0.04374194145202637   | 3.944763379130921  |
|   9   | 25600 |  0.17142486572265625   | 3.919004507622624  |
|   10  | 51200 |   0.7496669292449951   | 4.373151620009791  |
+-------+-------+------------------------+--------------------+
```

Recursive Factorial:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 4

Running a doubling-experiment benchmark for compute_recursive_factorial ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

+-------+------+-----------------------+--------------------+
| Round | Size |        Runtime        |      Average       |
+-------+------+-----------------------+--------------------+
|   1   | 100  | 0.0001494884490966797 |         0          |
|   2   | 200  | 0.0002467632293701172 | 1.6507177033492824 |
|   3   | 400  |  0.002645730972290039 | 10.721739130434782 |
|   4   | 800  | 0.0016205310821533203 | 0.6125078850139677 |
+-------+------+-----------------------+--------------------+
```

Recursive Hashmap Factorial:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 4

Running a doubling-experiment benchmark for compute_hashmap_recursive_factorial ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

+-------+------+------------------------+---------------------+
| Round | Size |        Runtime         |       Average       |
+-------+------+------------------------+---------------------+
|   1   | 100  | 0.00025653839111328125 |          0          |
|   2   | 200  | 0.0024843215942382812  |  9.684014869888475  |
|   3   | 400  | 0.0011663436889648438  | 0.46948176583493284 |
|   4   | 800  |  0.002273082733154297  |  1.9488961569910057 |
+-------+------+------------------------+---------------------+
```
Iterative Fibonacci:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for compute_iterative_fibonacci ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  | 1.9550323486328125e-05 |         0          |
|   2   |  200  | 2.3365020751953125e-05 | 1.1951219512195121 |
|   3   |  400  | 4.601478576660156e-05  | 1.969387755102041  |
|   4   |  800  | 0.00010752677917480469 | 2.3367875647668392 |
|   5   |  1600 | 0.00024056434631347656 | 2.237250554323725  |
|   6   |  3200 |  0.00058746337890625   | 2.4420218037661052 |
|   7   |  6400 | 0.0015387535095214844  | 2.6193181818181817 |
|   8   | 12800 | 0.0047414302825927734  | 3.081344902386117  |
|   9   | 25600 |  0.015990734100341797  | 3.3725549353849247 |
|   10  | 51200 |  0.05477547645568848   | 3.425451021321008  |
+-------+-------+------------------------+--------------------+
```
Bcopies_Oft:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for bcopies_oft ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  |    3.0517578125e-05    |         0          |
|   2   |  200  |  4.1961669921875e-05   |       1.375        |
|   3   |  400  | 8.034706115722656e-05  | 1.9147727272727273 |
|   4   |  800  | 0.00015974044799804688 | 1.9881305637982196 |
|   5   |  1600 | 0.00032019615173339844 | 2.0044776119402985 |
|   6   |  3200 | 0.0006425380706787109  | 2.0067014147431124 |
|   7   |  6400 |  0.001272439956665039  | 1.9803339517625231 |
|   8   | 12800 |  0.002610921859741211  | 2.0519018175004686 |
|   9   | 25600 |  0.005128383636474609  | 1.9642041822664598 |
|   10  | 51200 |  0.010424137115478516  | 2.0326359832635985 |
+-------+-------+------------------------+--------------------+
```

Mcopies_Ofc:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for mcopies_ofc ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+-----------------------+--------------------+
| Round |  Size |        Runtime        |      Average       |
+-------+-------+-----------------------+--------------------+
|   1   |  100  | 3.123283386230469e-05 |         0          |
|   2   |  200  | 4.553794860839844e-05 | 1.4580152671755726 |
|   3   |  400  | 8.630752563476562e-05 | 1.8952879581151831 |
|   4   |  800  | 0.0001671314239501953 | 1.9364640883977902 |
|   5   |  1600 | 0.0003399848937988281 | 2.034236804564907  |
|   6   |  3200 |    0.00067138671875   | 1.9747545582047685 |
|   7   |  6400 | 0.0013196468353271484 | 1.9655539772727273 |
|   8   | 12800 |  0.002727031707763672 | 2.0664859981933152 |
|   9   | 25600 |  0.005332469940185547 | 1.9554117852771464 |
|   10  | 51200 |  0.010961294174194336 | 2.0555754269873914 |
+-------+-------+-----------------------+--------------------+
```

Mcopies_Of:
```
****************************************************************
*          Speed-Surprises Simple Benchmarking Tool            *
****************************************************************

Please specify a number of rounds: 10

Running a doubling-experiment benchmark for mcopies_of ...

Running round 1 with size of 100 ...

Running round 2 with size of 200 ...

Running round 3 with size of 400 ...

Running round 4 with size of 800 ...

Running round 5 with size of 1600 ...

Running round 6 with size of 3200 ...

Running round 7 with size of 6400 ...

Running round 8 with size of 12800 ...

Running round 9 with size of 25600 ...

Running round 10 with size of 51200 ...

+-------+-------+------------------------+--------------------+
| Round |  Size |        Runtime         |      Average       |
+-------+-------+------------------------+--------------------+
|   1   |  100  |    3.0517578125e-05    |         0          |
|   2   |  200  | 4.124641418457031e-05  |     1.3515625      |
|   3   |  400  | 0.00016927719116210938 | 4.104046242774566  |
|   4   |  800  | 0.00039887428283691406 | 2.3563380281690143 |
|   5   |  1600 | 0.0012552738189697266  | 3.147041243275553  |
|   6   |  3200 |  0.004535675048828125  |  3.61329534662868  |
|   7   |  6400 |  0.018512248992919922  | 4.081476030277544  |
|   8   | 12800 |  0.07204484939575195   | 3.8917394328104473 |
|   9   | 25600 |   0.2595362663269043   | 3.602426384448901  |
|   10  | 51200 |   1.1731202602386475   | 4.520062944733201  |
+-------+-------+------------------------+--------------------+
```

**Comment by lussierc** [comment]
@huangs1 Thanks for adding these results using the tool!

**Comment by enpuyou** [comment]
Not gonna merge at this point

**Pull request closed without merging**
